[program:biokg_h37_stable]
environment=PROC_NAME="biokg_h37_stable"
directory=/workspace/biokg_h37
command=/bin/bash /workspace/biokg_h37/biokg/scripts/run_h37_stable.sh
autostart=false
autorestart=false
startsecs=2
exitcodes=0
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
