[program:biokg_mn1]
environment=PROC_NAME="biokg_mn1"
directory=/workspace/biokg_mn1
command=/bin/bash /workspace/biokg_mn1/biokg/scripts/run_masked_neighborhood.sh
autostart=false
autorestart=false
startsecs=2
exitcodes=0
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
